### ISSUE TITLE
Question about getting ground truth

### ISSUE THREAD

**Issue by whu-lyh** [ZhouZijie77/LCPR#2]
There might be a bug or type mistake when searching the positives? The `num_db` should be `num_query` during KNN module. Can you explain it? thanks
```
 def getPositives(self):
      # positives for evaluation are those within trivial threshold range
      # fit NN to find them, search by radius
      if self.positives is None:
          knn = NearestNeighbors(n_jobs=-1)
          dataset = np.ascontiguousarray(self.dataset[:self.num_db, 1:])
          knn.fit(dataset)
          self.positives = list(knn.radius_neighbors(self.dataset[self.num_db:, 1:], radius=self.nonTrivPosDistThres, return_distance=False))
      return self.positives
```

**Comment by ZhouZijie77** [comment]
Hello @whu-lyh,

Thanks for your interest in our work! Note the `:` after `num_db` here, indexing the query samples in the `self.dataset`.

**Comment by whu-lyh** [comment]
Oops, My bad. I missed the line `self.dataset = np.concatenate((data_base, query), axis=0)` at `__init__()` function.
And I wonder that what is the difference between using `sklearn` and `faiss` for knn searching?

**Comment by ZhouZijie77** [comment]
`faiss` is specifically designed for large-scale vector retrieval. So `faiss` is generally more efficient than `knn` in `sklearn`.

**Comment by whu-lyh** [comment]
Thanks for your reply.
