### ISSUE TITLE
Autoplace evaluation

### ISSUE THREAD

**Issue by Dcasadoherraez** [ZhouZijie77/LCPR#3]
Hello!
Thanks so much for providing the code for LCPR!
I was wondering about how is the Autoplace evaluation being performed. How are you getting 90% Recall@1 on the test set using a single scan and no RCS reranking, while in the original paper the result is 78.9% for 7 scans using RCS reranking.
Thanks in advance,
Best,
Dani

**Comment by ZhouZijie77** [comment]
Hello, our data organization is different from Autoplace's. Specifically, we create the database set from the entire data split to ensure that the database is up-to-date, while autoplace creates the database only from the first 105 days. Moreover,  we actually use 7 scans with dynamic points removed to generate the radar images for the evaluation of Autoplace. The "single frame" for Autoplace in our paper actually means not using the Temporal Encoder.

**Comment by Dcasadoherraez** [comment]
Sounds good! Thanks for the information 😄
