### ISSUE TITLE
Reproduce Pointnetvlad, Adafusion and Minkloc++ On NuScenes

### ISSUE THREAD

**Issue by FudongGe** [ZhouZijie77/LCPR#4]
Hi, thanks for your great work.
I have one question.
How do you reproduce pointnetvlad, adafusion and minkloc++ methods on nuscenes? They seem to use similar types of point cloud data, but I am not sure how do you handle the point cloud data of nuscenes. Could you please provide some information? Or if possible, the relevant code？
Thanks in advance.

**Comment by ZhouZijie77** [comment]
Hello, we process the point cloud data based on the [Matlab code](https://github.com/mikacuy/pointnetvlad/blob/master/submap_generation/generate_submaps.m) provided by PointNetVLAD, including shifting, rescaling the point cloud to zero mean and inside the range of [-1, 1], and downsampling the pointcloud. For faster processing, you can refer to this [repo](https://github.com/ZJU-Robotics-Lab/Voxelization_API) for point cloud voxelization with GPU.

**Comment by FudongGe** [comment]
Thanks for your reply.
