### ISSUE TITLE
消融后效果比融合的效果还好

### ISSUE THREAD

**Issue by Joker001014** [ZhouZijie77/LCPR#5]
![Uploading 111.png…]()
您好，我修改了您的代码，分别进行了视觉PR和雷达PR预测，但发现分别使用视觉分支IE或者雷达分支LE进行训练及预测，其预测结果均比融合后预测结果还要好（如图，黄-融合，紫-视觉，绿-雷达），请问这是什么原因呢，是我修改结构删除分支时漏改了什么代码吗？望指教，谢谢您！

**Comment by fulizi123** [comment]
您好，请问您后续实验结果如何呢？我也碰到了这个问题，请问如何解释呢？
